name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: nu {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: LedgerHQ/actions/setup-nu@feat/nushell
        with:
          lib-version: feat/nushell

      - name: Run a multi-line script
        id: loul
        run: |
          nugha push-output {bonjour: trucmachin}
          echo $env.GITHUB_OUTPUT

      - name: Test output
        run: |
          echo ${{ steps.loul.outputs.bonjour }}
